Lab9
Shaskels/AndroidCourse pull request #10
Opened 2024-12-11 10:05 UTC by Shaskels

Можно обновлять список с pull to refresh

2024-12-14 18:19 UTC, Romchirik commented on Lab9/app/src/main/java/com/example/lab9/data/datasource/CurrencyListRemoteDataSource.kt
> +    private fun convertToList(currenciesResponse: CurrenciesResponse): Single<List<Currency>> {
Нужно обобщить парсинг валют, тут получается, что если с апи придет новая валюта то оно не отобразится. Также, если какую-то валюту уберут, то все взорвется))

2024-12-14 18:21 UTC, Romchirik requested changes
![image](https://github.com/user-attachments/assets/795b0a45-1c8d-473f-91c5-f94ffa20ddc7)
Немного нужно еще поправить UI/UX, клавиатура перекрывает ввод текста + у меня на устройстве почему-то вообще текст не вводится(( (скорее всего потому что поле ввода из фокуса пропадает)

2024-12-15 07:31 UTC, Shaskels commented on Lab9/app/src/main/java/com/example/lab9/data/datasource/CurrencyListRemoteDataSource.kt
> +    private fun convertToList(currenciesResponse: CurrenciesResponse): Single<List<Currency>> {
Переделала под мапку, теперь не должно взорваться

2024-12-15 07:32 UTC, Shaskels commented on Lab9/app/src/main/java/com/example/lab9/data/datasource/CurrencyListRemoteDataSource.kt
> +    private fun convertToList(currenciesResponse: CurrenciesResponse): Single<List<Currency>> {
Перекрывание ввода тоже поправила

2025-01-06 06:32 UTC, merged