Lab2_2
Shaskels/AndroidCourse pull request #3
Opened 2024-10-05 10:35 UTC by Shaskels

2024-10-10 13:32 UTC, Romchirik requested changes

2024-10-10 13:32 UTC, Romchirik commented on Lab2_2/app/src/main/java/com/example/lab2_2/FirstFragment.kt
> +        val nextButton : Button = view.findViewById(R.id.button)
В onCreateView лучше не делать никаких операций кроме инфлейта, чтобы показать пользователю контент как можно быстрее, нужно все кроме инфлейта вынести в onViewCreated

2024-10-10 13:32 UTC, Romchirik commented on Lab2_2/app/src/main/java/com/example/lab2_2/FirstFragment.kt
> +                replace<SecondFragment>(R.id.navigation_container)
Го тут перейдем на add, с реплейсом предыдущий фрагмент будет пересоздаваться каждый раз при возврате, не оч оптимально получается

2024-10-10 13:32 UTC, Romchirik commented on Lab2_2/app/src/main/java/com/example/lab2_2/ThirdFragment.kt
> +            transaction?.popBackStack("Fragment1",FragmentManager.POP_BACK_STACK_INCLUSIVE)
Константу нужно вынести в  const переменную, над соответствующим классом

2024-10-12 11:07 UTC, Shaskels commented on Lab2_2/app/src/main/java/com/example/lab2_2/FirstFragment.kt
> +        val nextButton : Button = view.findViewById(R.id.button)
Вынесла все в onViewCreated

2024-10-12 11:07 UTC, Shaskels commented on Lab2_2/app/src/main/java/com/example/lab2_2/FirstFragment.kt
> +                replace<SecondFragment>(R.id.navigation_container)
Хорошо

2024-10-12 11:08 UTC, Shaskels commented on Lab2_2/app/src/main/java/com/example/lab2_2/ThirdFragment.kt
> +            transaction?.popBackStack("Fragment1",FragmentManager.POP_BACK_STACK_INCLUSIVE)
Сделала companion object

2024-10-17 13:28 UTC, Romchirik approved these changes

2024-10-21 06:25 UTC, merged