Lab3
Shaskels/AndroidCourse pull request #4
Opened 2024-10-05 10:35 UTC by Shaskels

2024-10-10 13:43 UTC, Romchirik requested changes

2024-10-10 13:43 UTC, Romchirik commented on Lab3/app/src/main/java/com/example/lab3/CustomAdapter.kt
> +            val song = item as Song
Если передам рекламу, то прилажка взорвется, вьюхолдеры должны быть максимально тупыми и только мапить значения из модельки на UI с минимумом логики

По итогу тут надо принимать Song, а не ListItem

2024-10-10 13:43 UTC, Romchirik commented on Lab3/app/src/main/java/com/example/lab3/ListItem.kt
> +    enum class Type(value: Int) { Song(0), Advertisement(1) }
Value не используется. Вместо него используются ординалы, это плохо, лучше как раз запользовать вот этот value. С ординалами могут быть проблемы, если местами переставишь типы в енаме. Тут не взорвется, но вот если попробуешь сохранить енамчик по ординалу в базу, то потом может выстрелить в колено.

Вообще, для модельки айтема листа рекомендую заиспользовать sealed interface, имхо, но будет получше

2024-10-10 13:43 UTC, Romchirik commented on Lab3/app/src/main/java/com/example/lab3/ListItem.kt
> +    fun getListItemType(): Int
Можно заменить на val type: Int и переопределить в наследниках, чтобы каждый раз вызов метода не делать, а сразу в пропертю ходить

2024-10-10 13:43 UTC, Romchirik commented on Lab3/app/src/main/java/com/example/lab3/CustomAdapter.kt
> +                intent.putExtra("text1", item.title)
Все переиспользуемые константы нужно вынести над классом, к которому они относятся

2024-10-10 13:43 UTC, Romchirik commented on Lab3/app/src/main/java/com/example/lab3/CustomAdapter.kt
> +        holder.itemView.setOnClickListener{
Если после добавления рекламы ткнуть на песню, которая под вьюхой рекламы, то открывается экран рекламы, надо починить

2024-10-12 11:09 UTC, Shaskels commented on Lab3/app/src/main/java/com/example/lab3/CustomAdapter.kt
> +            val song = item as Song
Перенесла всю логику в onBindViewHolder, теперь там определяется какой bind вызывать

2024-10-12 11:11 UTC, Shaskels commented on Lab3/app/src/main/java/com/example/lab3/ListItem.kt
> +    enum class Type(value: Int) { Song(0), Advertisement(1) }
Поправила

2024-10-12 11:11 UTC, Shaskels commented on Lab3/app/src/main/java/com/example/lab3/ListItem.kt
> +    fun getListItemType(): Int
Поправила

2024-10-12 11:11 UTC, Shaskels commented on Lab3/app/src/main/java/com/example/lab3/CustomAdapter.kt
> +                intent.putExtra("text1", item.title)
Сделала companion object

2024-10-12 11:14 UTC, Shaskels commented on Lab3/app/src/main/java/com/example/lab3/CustomAdapter.kt
> +        holder.itemView.setOnClickListener{
Добавила notifyItemRangeChanged при обновлении списка, теперь работает верно

2024-10-17 13:27 UTC, Romchirik requested changes

2024-10-17 13:27 UTC, Romchirik commented on Lab3/app/src/main/java/com/example/lab3/CustomAdapter.kt
> +        const val TEXT1_KEY = "text1"
Тут пара вопросов есть
1) Название константы ни о чем не говорит, надо переназвать 
2) Адаптер пользуется контрактом для открытия активити деталей, размещать константы в адаптере не совсем верно, потому что именно активити задает контракт для открытия, собственно, себя. Нужно перенести константы в активити

2024-10-17 13:27 UTC, Romchirik commented on Lab3/app/src/main/java/com/example/lab3/Song.kt
> +        get() = ListItem.Type.SONG.value
А зачем гет если можно просто `override val type: Int = ListItem.Type.SONG.value`

2024-12-08 12:24 UTC, merged